#ifndef _SSV_EFUSE_H_
#define _SSV_EFUSE_H_
#include "dev.h"
struct efuse_map
{
	u8 offset;
	u8 byte_cnts;
	u16 value;
};
enum efuse_data_item {
	EFUSE_R_CALIBRATION_RESULT = 1,
	EFUSE_SAR_RESULT,
	EFUSE_MAC,
	EFUSE_CRYSTAL_FREQUENCY_OFFSET,
	EFUSE_TX_POWER_INDEX_1,
	EFUSE_TX_POWER_INDEX_2,
	EFUSE_CHIP_IDENTITY
};
#define EFUSE_HWSET_MAX_SIZE (256 - 32)
#define EFUSE_MAX_SECTION_MAP (EFUSE_HWSET_MAX_SIZE >> 5)
#define SSV_EFUSE_ID_READ_SWITCH 0xC2000128
#define SSV_EFUSE_ID_RAW_DATA_BASE 0xC200014C
#define SSV_EFUSE_READ_SWITCH 0xC200012C
#define SSV_EFUSE_RAW_DATA_BASE 0xC2000150
void efuse_read_all_map(struct ssv_hw *sh);
#endif
